# Global mode - controls the default way Toxic Skies makes the air poisonous
# Mode 1 - Always raining. Air always toxic.
# Mode 2 - Rains now and then (like normal). Air always toxic.
# Mode 3 - Rains now and then (like normal). Air only toxic when raining.
Mode: 1

SecondsBetweenPolls: 10
AboveGroundDamage: 1
AboveGroundMessage: The air burns your lungs and saps your strength!
CleanAirMessage: The air is clean here.
PumpkinHelmetBreakChancePercent: 8
PumpkinHelmetBreakMessage: Your pumpkin helmet falls apart in your hands!
PumpkinHelmetSurviveMessage: Your pumpkin helmet weakens.
PumpkinHelmetMaterial: PUMPKIN

# For a complete list, see: http://jd.bukkit.org/rb/apidocs/org/bukkit/potion/PotionEffectType.html
PoisonEffects:
- SLOW
- SLOW_DIGGING
- HUNGER

# Only the worlds listed below will have toxic air
# To override the mode of the world, add a pipe and the mode number to the end
#    ex:  - myWorld|2
# By default, all affected worlds inherit the global mode
AffectedWorlds:
- world